actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 90 days (based on creation date). Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: age
      source: creation_date
      direction: older
      timestring: '%Y.%m.%d.%H.%M.%S.'
      unit: hours
      unit_count: 1
